### ISSUE TITLE
Requirements Error

### ISSUE THREAD

**Issue by r3l1c7** [3a7/SQLi-Hunter-v2#1]
Any idea what's causing this issue?

$ pip3 install -r requirements.txt       
Defaulting to user installation because normal site-packages is not writeable
Collecting requests==2.28.1
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting schedule==1.1.0
  Using cached schedule-1.1.0-py2.py3-none-any.whl (10 kB)
Collecting user-agent==0.1.10
  Using cached user_agent-0.1.10.tar.gz (20 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hc6t1ydk/user-agent_5d05addb72194e6fa553c7e763aa2694/setup.py", line 10, in <module>
          setup(
        File "/home/kali/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/home/kali/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          dist = MinimalDistribution(attrs)
        File "/home/kali/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 57, in __init__
          super().__init__(filtered)
        File "/home/kali/.local/lib/python3.10/site-packages/setuptools/dist.py", line 473, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
          return SelectableGroups.load(eps).select(**params)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
          ordered = sorted(eps, key=by_group)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1018, in <genexpr>
          eps = itertools.chain.from_iterable(
        File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
          k = key(element)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 943, in _normalized_name
          or super()._normalized_name
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
          return Prepared.normalize(self.name)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
          return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
        File "/usr/lib/python3.10/re.py", line 209, in sub
          return _compile(pattern, flags).sub(repl, string, count)
      TypeError: expected string or bytes-like object
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by 3a7** [comment]
It looks like you're getting an error while downloading the `user-agent` module. To solve this try downloading it separately by typing `pip install user-agent` or `pip3 install user-agent`. If the error persists it means that the error is within the `user-agent` package which is something I'm not capable of fixing.
